apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: cep-project1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name:  mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
              name: project1secret
              key: value_mysql
              optional: false
          - name: MYSQL_DATABASE 
            valueFrom:
             secretKeyRef:
              name: project1secret
              key: value_mysqldb
              optional: false
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: myvol1 
            mountPath: /var/lib/mysql
      volumes:
      - name: myvol1
        persistentVolumeClaim:
         claimName: mypvc1
